@startuml GRB_Gestion_Usuarios_Administradores

title Módulo GRB - Gestión de Usuarios y Administradores

'Configura de estilo
left to right direction
skinparam packageStyle rectangle

skinparam usecase {
    BackgroundColor #EDE9FC
    BorderColor #534AB7
    ArrowColor #534AB7
    ActorBorderColor #3C3489
    ActorBackgroundColor #EEEDFE
}

skinparam note {
    BackgroundColor #E8F8F5
    BorderColor #1ABC9C
}

' Definición de actores, casos de uso y relaciones
rectangle {

    'Actores
    actor "Usuario" as USR
    actor "Administrador" as ADM

    'Casos de uso
    usecase "Registrar cuenta" as CU1 
    usecase "Actualizar información de cuenta" as CU2 
    usecase "Desactivar cuenta" as CU3

    usecase "Asignar rol a usuario" as CU4 
    usecase "Definir permisos de rol" as CU5

    usecase "Iniciar sesión" as CU6 

    usecase "Actualizar perfil" as CU7
    usecase "Recuperar contraseña" as CU8 

    usecase "Enviar token de restablecimiento" as CU9 

    ' Relación include
    CU8 .> CU9 : <<include>>

}

' Relaciones Usuario
USR --> CU6
USR --> CU8
USR --> CU7

' Relaciones Administrador
ADM --> CU6
ADM --> CU1
ADM --> CU2
ADM --> CU3
ADM --> CU4
ADM --> CU5

@enduml
